################################### Languages #####################################

[uk]
  locale = "uk-ua"
  label = "UA"
  contentDir = "content/ukrainian"
  weight = 1
  copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"

[en]
  locale = "en-us"
  label = "EN"
  contentDir = "content/english"
  weight = 2
  copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"


