############# Ukrainian navigation ##############

# main menu
[[main]]
name = "Головна"
url = "/"
weight = 1

[[main]]
name = "Про компанію"
url = "/about/"
weight = 2


[[main]]
name = "Блог"
url = "/blog/"
weight = 3

[[main]]
weight = 4
name = "Категорії"
hasChildren = true

  [[main]]
  parent = "Категорії"
  name = "Промислова автоматизація"
  url = "/categories/industrial-automation/"
  weight = 1

  [[main]]
  parent = "Категорії"
  name = "ШІ та Комп’ютерний зір"
  url = "/categories/ai-computer-vision"
  weight = 2

    [[main]]
  parent = "Категорії"
  name = "Робототехніка"
  url = "/categories/robotics"
  weight = 3

  [[main]]
  parent = "Категорії"
  name = "Енергоменеджмент"
  url = "/categories/energy-management/"
  weight = 4

   [[main]]
  parent = "Категорії"
  name = "Кібербезпека"
  url = "/categories/cybersecurity/"
  weight = 5

  [[main]]
  parent = "Категорії"
  name = "Широкий кут"
  url = "/categories/the-big-picture/"
  weight = 6

  [[main]]
  parent = "Категорії"
  name = "Пісочниця"
  url = "/categories/sandbox/"
  weight = 7


[[main]]
name = "Контакти"
url = "/contact/"
weight = 5



