############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about/"
weight = 2


[[main]]
name = "Blog"
url = "/blog/"
weight = 3

[[main]]
weight = 4
name = "Categories"
hasChildren = true

  [[main]]
  parent = "Categories"
  name = "Industrial Automation"
  url = "/categories/industrial-automation/"
  weight = 1

  [[main]]
  parent = "Categories"
  name = "AI & Robotics"
  url = "/categories/ai-robotics"
  weight = 2

  [[main]]
  parent = "Categories"
  name = "Energy Management"
  url = "/categories/energy-management/"
  weight = 3

  [[main]]
  parent = "Categories"
  name = "The Big Picture"
  url = "/categories/the-big-picture/"
  weight = 4

  [[main]]
  parent = "Categories"
  name = "Sandbox"
  url = "/categories/sandbox/"
  weight = 5


[[main]]
name = "Contact"
url = "/contact/"
weight = 5



